language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: HYFSm84gCi+EnE3hDeRfPFojhfPx7RS7xfP2cYs+tzOvE2DdL62D4ZA/bnBTCbIl4FyOKxS/3biLYu40d8UIjDYvMgx8xaT/byJB6iw4my9vnzkFl2NcbBNQA0NvoU8lBrS/zXrbz3U/JMLNDXlGDFx/GTMmvAYt2Hrttq9kxD4=
    - secure: Yfaf3JfZ7QWuEqOmExFD81KD0SDiAIB84x122zCYpcHCyqqAjWQw2v7+YBBR3F3m0sdMhrVuj/gBkmccEU/M3KLYR8jm9DiPfeenW2mdJwUBdcmM+9DCeYtnkZx8DYo3Uxpxi0WkvXmED6l6mkWHyPVSi3que9h1t3aOv/zt+2I=
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --quiet --upgrade pip
- pip install --quiet --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --quiet --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.db.voxforge import get_config; print(get_config())'
- ./bin/coverage run --source=bob.db.voxforge ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
